// <auto-generated />
namespace NaproKarta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class napro3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(napro3));
        
        string IMigrationMetadata.Id
        {
            get { return "201709041511255_napro3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
